### PR TITLE
SyntheticDOM expects attributes to be provided as Object { name, value }

### PR DESCRIPTION
**Pull request by maiers**
See: https://github.com/sstur/synthetic-dom/blob/master/src/SyntheticDOM.js#L3

This is likely the root cause for: https://github.com/sstur/react-rte/issues/121

### CODE REVIEW

**Comment by uyson** [comment]
waiting for merge

**Comment by nuclearspike** [comment]
I'd like to see this merged as well. 👍

**Comment by ccastillop** [comment]
hello,
What about this fix?

**Comment by maiers** [comment]
Hi Simon / @sstur 

could we have this pull request merged anytime soon? Or is there any reason this will not work for you? I really like react-rte, but with images and links broken it's a pain in the ass to remeber to patch them manually on each build.

Greetings,
Sebastian

**Comment by Calyhre** [comment]
🆙 🙏

**Comment by mxstbr** [comment]
Does this also fix #1 by chance? (blockquotes and code blocks)

**Review by sstur — APPROVED** [review]
Oh wow, this has been waiting for review for a long time. Thanks for your contribution @maiers!

**Comment by maiers** [comment]
@mxstbr It does fix broken code blocks. It does not fix an blockquotes though.

**Pull request merged**
